language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "stable"
addons:
  apt:
    packages:
      - default-jre
before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - grunt
notifications:
  email: false
