env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "stable"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - grunt
notifications:
  email: false
